# Generated by Django 6.0.4 on 2026-05-09 15:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModelsApp', '0002_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Number',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=17)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Numbers',
            },
        ),
        migrations.AlterModelOptions(
            name='person',
            options={},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='person',
            name='person_name_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='product_name_idx',
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='person',
            name='created_at',
        ),
    ]
